name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11
        cc: 
          - gcc
          - clang
        arch:
          - amd64
          - arm64
          - arm
          - ppc64le
          - s390x

    continue-on-error: true

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v2

    - name: Resolve dependencies (Ubuntu)
      run: |
        sudo apt-get update && \
        sudo apt-get install autoconf \
          fonts-freefont-ttf \
          imagemagick \
          libqrencode-dev \
          zbar-tools
      if: contains(matrix.os, 'ubuntu')

    - name: Resolve dependencies (macOS)
      run: |
        brew install autoconf \
          imagemagick \
          qrencode \
          zbar
        brew tap homebrew/cask-fonts
        brew install --cask font-freefont
        convert -font FreeMono label:"Unable to revert mtime: /Library/Fonts fix" png:- > /dev/null
      if: contains(matrix.os, 'macos')

    - name: Build
      run: make

    - name: Test (Ubuntu)
      shell: 'script --return --quiet --command "bash {0}"'
      if: contains(matrix.os, 'ubuntu')
      run: make test

    - name: Test (macOS)
      shell: bash -l {0}
      if: contains(matrix.os, 'macos')
      run: make test

    - name: Print test logs
      if: ${{ failure() }}
      run: cat tests.dir/*/*.log

    - name: Install
      run: PREFIX=/usr/local sudo make install

    - name: Run (Ubuntu)
      shell: 'script --return --quiet --command "bash {0}"'
      if: contains(matrix.os, 'ubuntu')
      run: /usr/local/bin/qr Success

    - name: Run (macOS)
      shell: bash -l {0}
      if: contains(matrix.os, 'macos')
      run: /usr/local/bin/qr Success

    - name: Uninstall
      run: PREFIX=/usr/local sudo make uninstall
