name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Resolve dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install autoconf \
          fonts-freefont-ttf \
          imagemagick \
          libqrencode-dev \
          zbar-tools
    - name: Build
      run: make
    - name: Test
      run: make test
    - name: Print test logs
      if: ${{ always() }}
      run: cat tests.dir/*/*.log
    - name: Install
      run: PREFIX=/usr/local sudo make install
    - name: Run
      run: /usr/local/bin/qr Success
    - name: Uninstall
      run: PREFIX=/usr/local sudo make uninstall
